### ISSUE TITLE
增加搜索功能

### ISSUE THREAD

**Issue by JobsDong** [JobsDong/zhihudaily#4]

**Comment by halfcrazy** [comment]
搜索功能似乎有问题，搜语言时
500 Server Error.
'int' object has no attribute '__getitem__'

**Comment by JobsDong** [comment]
@halfcrazy 恩，是的，我把功能关了。因为搜索的性能非常不好。这几天优化一下性能，可能会重新加上这个功能。

**Comment by halfcrazy** [comment]
@JobsDong https://github.com/dbbbit/ninja-search 这个项目用的elasticsearch感觉效果还不错

**Comment by JobsDong** [comment]
@halfcrazy OK， 我看一下。3Q
